name: Continuous Integration

on:
  pull_request:
    branches: ['1.x']
  push:
    branches: ['1.x']

jobs:
  phpunit:
    name: PHPUnit (PHP ${{ matrix.php-version }} - Symfony ${{ matrix.symfony-version }})
    runs-on: ubuntu-20.04
    env:
      SYMFONY_REQUIRE: ${{ matrix.symfony-version }}

    strategy:
      matrix:
        php-version:
          - '8.0'
          - '8.1'
        symfony-version:
          - '5.3.*'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Install PHP with pcov
        uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
          php-version: ${{ matrix.php-version }}
          extensions: zip

      - name: Install Symfony Flex
        run: composer global require --no-progress --no-scripts --no-plugins symfony/flex

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1

      - name: Run PHPUnit
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        if: matrix.php-version == '8.0' && matrix.symfony-version == '5.3.*'
